---
title: Characterizing Color Term Knowledge in Adults in the Peruvian Shipibo Tribe
author: "Danielle Kellier, Martin Fortier, and Mike Frank"
date: "`r Sys.Date()`"
output:
  html_document:
  highlight: tango
theme: spacelab
pdf_document: default
---


```{r setup, echo = FALSE}

knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r, cache = FALSE, echo = FALSE}
library(tidyverse)
library(magrittr)
library(ggplot2)
library(htmlTable)
library(DT)
library(plotly)
library(feather)
library(viridis)
library(ggthemes)
library(stringr)
library(lme4)
library(readxl)

```


Load and format CSV data from current study along with World Color Survey Data

```{r}

source("../helpers/load_and_process.R")

min_consensus <- 15
min_edge_chips <- 3
age_int <- 1
refresh_data <- TRUE


```


```{r}
shipibo_euclid_dist <- shipibo_chip_set %>%
  select(shipibo, chip_id) %>%
  separate_rows(shipibo, sep = "/") %>%
  mutate(k = 1) %>%
  left_join(select(color_chip_data, "#cnum", "L*", "a*", "b*"), by = c("chip_id" = "#cnum")) %>%
  full_join(shipibo_chip_set %>%
              select(shipibo, chip_id) %>%
              separate_rows(shipibo, sep = "/") %>%
              mutate(k = 1) %>%
              left_join(select(color_chip_data, "#cnum", "L*", "a*", "b*"), by = c("chip_id" = "#cnum")), 
            by = "k") %>%
  filter(shipibo.x != shipibo.y) %>%
  mutate(dist = sqrt((`L*.x` - `L*.y`)^2 + (`a*.x` - `a*.y`)^2 + (`b*.x` - `b*.y`)^2)) %>%
  select(starts_with("shipibo"), starts_with("chip_id"), dist)

spanish_euclid_dist <- spanish_chip_set %>%
  select(spanish, chip_id) %>%
  mutate(k = 1) %>%
  left_join(select(color_chip_data, "#cnum", "L*", "a*", "b*"), by = c("chip_id" = "#cnum")) %>%
  full_join(spanish_chip_set %>%
              select(spanish, chip_id) %>%
              mutate(k = 1) %>%
              left_join(select(color_chip_data, "#cnum", "L*", "a*", "b*"), by = c("chip_id" = "#cnum")), 
            by = "k") %>%
  filter(spanish.x != spanish.y) %>%
  mutate(dist = sqrt((`L*.x` - `L*.y`)^2 + (`a*.x` - `a*.y`)^2 + (`b*.x` - `b*.y`)^2)) %>%
  select(starts_with("spanish"), starts_with("chip_id"), dist)

boundary_chips <- naming_data %>%
  select(subj, chip_id, color_cat) %>%
  mutate(set = ifelse((chip_id %% 2) == 0, 'even', 'odd')) %>%
  split(.$set) %>%
  map_df(function(x) {
    x %>%
    group_by(chip_id, color_cat) %>%
    summarise(n = n()) %>%
    group_by(chip_id) %>%
    mutate(perc = 100*n/sum(n)) %>%
    select(-n)
  }) %>%
  group_by(chip_id) %>%
  filter(perc >= min_consensus) %>%
  mutate(perc = 1) %>%
  filter(n() >= 2) %>%
  summarise(color_cats = paste0(color_cat, collapse = ", "))

shipibo_boundary <- crossing(Color_1 = shipibo_terms, 
         Color_2 = shipibo_terms) %>%
  filter(Color_1 != Color_2) %>%
  rowwise() %>%
  do(Color_1 = first(.$Color_1),
     Color_2 = first(.$Color_2),
     boundary_chips = sum(apply(sapply(c(.$Color_1, .$Color_2), grepl, boundary_chips$color_cats), 1, all)))%>%
  summarise(Color_1 = first(Color_1),
            Color_2 = first(Color_2),
            sum_chips = sum(boundary_chips),
            adjacency = ifelse(sum(boundary_chips) >= min_edge_chips, 1, 0)) %>%
  left_join(shipibo_euclid_dist, by = c("Color_1" = "shipibo.x", "Color_2" = "shipibo.y"))

shipibo_boundary %<>%
  bind_rows(  shipibo_boundary %>%
    filter(`Color_1` %in% c("Pei", "Xo", "Ami", "Poa") |
             `Color_2` %in% c("Pei", "Xo", "Ami", "Poa")) %>%
    mutate_at(vars(starts_with("Color")), 
              funs(str_replace_all(., 
                                   c("(\\bPei\\b)|(\\bXo\\b)" = "Pei/Xo",
                                     "(\\bAmi\\b)|(\\bPoa\\b)" = "Ami/Poa")
                                       ))) %>%
    group_by(`Color_1`, `Color_2`) %>%
    summarise(sum_chips = sum(sum_chips, na.rm = T),
              adjacency = ifelse(sum(adjacency, na.rm = T) >= 1, 1, 0),
              chip_id.x = first(chip_id.x),
              chip_id.y = first(chip_id.y),
              dist = first(dist)) %>%
    filter( is.na(chip_id.x) | chip_id.x != chip_id.y))

spanish_boundary <- as.data.frame(as.matrix(Matrix::forceSymmetric(
  as.matrix(read_csv("../data/adjacent_spanish_labels.csv")[,-1]),uplo="U"))) %>%
  rownames_to_column("Color_1") %>%
  gather(key = "Color_2", value = "adjacency", Blanco:Rosa) %>%
  filter(Color_1 != Color_2) %>%
  left_join(spanish_euclid_dist, by = c("Color_1" = "spanish.x", "Color_2" = "spanish.y")) %>%
  rename("Chip ID_1" = "chip_id.x", "Chip ID_2" = "chip_id.y") %>%
  select(starts_with("Color"), starts_with("Chip"), adjacency, dist)
```


```{r}

clean_child_data <- function(df, min_consensus = 10) {

  # child_string_spelling_list <- "`Agua` = c('agna', 'agua', 'agur'), `Amarillo` = c('amarilla', 'amarillo'), `Ami` = c('ami'), `Azul` = c('azul'), `Barin Poi` = c('bari', 'barri', 'barrinpui'), `Blanco` = c('blanco'), `Celeste` = c('celeste'), `Gris` = c('gris'), `Jene` = c('jene', 'jenekeska'), `Jimi` = c('jimi'), `Joa` = c('joa'), `Joshin` = c('joshin', 'toshin', 'joshin metsashoko', 'joshinshama'), `Joxo` = c('joxo', 'joxo jakwokawa', 'joxo metsa'), `Kari` = c('carri'), `Mai` = c('mai'), `Mancoa Pei` = c('mancoapei', 'mancoa pei'), `Manxan` = c('manxan'), `Marron` = c('marron'), `Morado` = c('morado'), `Nai` = c('nai', 'nai (lluvia)'), `Nai Wiso` = c('nai wisoa', 'naiwiso'), `Naranja` = c('anarando', 'narango', 'naranja', 'naranjada', 'naranjado', 'naranjo', 'narranxa'), `Negro` = c('negro'), `Oxne` = c('oxe'), `Panshin` = c('panshin', 'panshintani', 'panshinshima', 'Panshinshima'), `Pei` = c('pei'), `Poa` = c('pua'), `Rojo` = c('rojo'), `Rosa` = c('rosa', 'rosada', 'rosado'), `Unpasx` = c('unpasx', 'unpax'), `Verde` = c('verde', 'verdesito', 'shokouerde'), `Violeta` = c('bioleta', 'violeta', 'metsa shoko violeta'), `Wiso` = c('wiso', 'wisoshama'), `Xo` = c('xo'), `Yame` = c('yame'), `Yankon` = c('yakon', 'yakun', 'yankon', 'yankontani', 'yankun', 'yakonshama', 'Yakunshama', 'yankon pasna', 'yankoncha')"
  # 
  # child_spelling_list <- eval(parse(text = paste0("c(",child_string_spelling_list,")")))

  adult_naming_consensus <- naming_data %>%
    select(subj, chip_id, color_cat) %>%
    filter(chip_id %in% shipibo_chip_set$chip_id) %>%
    mutate(set = ifelse((chip_id %% 2) == 0, 'even', 'odd')) %>%
    split(.$set) %>%
    map_df(function(x) {
      x %>%
      group_by(chip_id, color_cat) %>%
      summarise(n = n()) %>%
      group_by(chip_id) %>%
      mutate(perc = 100*n/sum(n)) %>%
      select(-n)
    }) %>%
    arrange(chip_id) %>%
    filter(perc >= min_consensus) %>%
    select(-perc)
  
  
  both_chip_sets <- full_join(select(spanish_chip_set, -code), 
                              shipibo_chip_set, 
                              by = c("spanish", "munsell_code", "chip_id")) %>%
    mutate(
           both_langs = ifelse(!is.na(shipibo),
                               str_c(spanish, shipibo, sep = ", "), spanish))
  

  
  if (first(df$task) == "Comprehension") {
    
    df <- df %>%
      mutate(prompt = as.character(forcats::fct_collapse(prompt,
                                            `Ami/Poa` = c("morado"),
                                            `Barin Poi` = c("mierda sol"),
                                            `Joshin` = c("rojo"),
                                            `Joxo` = c("blanco"),
                                            `Nai` = c("celeste"),
                                            `Panshin` = c("amarillo"),
                                            `Pei/Xo` = c("verde"),
                                            `Wiso` = c("negro"),
                                            `Yankon` = c("azul/verde"),
                                            `Amarillo` = c("AM"),
                                            `Celeste` = c("AZ"),
                                            `Blanco` = c("BL"),
                                            `Gris` = c("GR"),
                                            `Marron` = c("MRN"),
                                            `Morado` = c("MRD"),
                                            `Naranja` = c("NR"),
                                            `Negro` = c("NG"),
                                            `Rojo` = c("RJ"),
                                            `Rosa` = c("RS"),
                                            `Verde` = c("VD")
                                            )),
           response = as.character(forcats::fct_collapse(response,
                                              `245` = c("Rojo", "rojo", "roja", "245"),
                                              `312` = c("Negro", "negro", "312"),
                                              `234` = c("Verde", "verde", "234"),
                                              `274` = c("Blanco", "blanco", "Joxo", "joxo", "274"),
                                              `320` = c("Mierda Sol", "miarda", "miarda del sol", "320"),
                                              `1` = c("Celeste", "celeste", "1"),
                                              `325` = c("Morado", "morada", "morado", "325"),
                                              `297` = c("Amarillo", "amarillo", "amarilla", "297"),
                                              `121` = c("121"),
                                              `291` = c("291"),
                                              `65` = c("65"),
                                              `266` = c("266"),
                                              `46` = c("46"))))
    
    
    if (first(df$language) == "Shipibo") {
      
      df <- df %>%
        filter((prompt %in% c("Wiso", "Panshin", "Nai", "Joxo", "Ami/Poa", "Barin Poi") & response_num == 1) | 
                 (prompt %in% c("Pei/Xo", "Joshin") & response_num <= 2) | 
                 (prompt == "Yankon" & response_num <= 4)) %>%
        left_join(adult_naming_consensus %>% ungroup() %>%
                    add_row(chip_id = c(325, 320, 234), color_cat = c('Ami/Poa', 'Barin Poi', 'Pei/Xo')) %>%
                    group_by(color_cat) %>%
                    summarise(chips = paste(chip_id, collapse = ", ")),
                  by = c("prompt" = "color_cat")) %>%
        left_join(both_chip_sets, by = c("prompt" = "shipibo")) %>%
        mutate(correct = ifelse(str_detect(chips, response), 1, 0),
               correct = ifelse(!is.na(response), correct, ifelse(response_num == 1, 0, NA)),
               spanish = ifelse(prompt == "Yankon", "Azul/Verde", spanish)) %>%
        left_join(select(shipibo_chip_set, shipibo, chip_id) %>%
                    mutate(chip_id = as.character(chip_id)), 
                  by = c("response" = "chip_id")) %>%
        left_join(shipibo_boundary, 
                  by = c("prompt" = "Color_1", "shipibo" = "Color_2"))
      
    } else if (first(df$language) == "Spanish") {
      df <- df %>%
        filter(response_num == 1) %>%
        left_join(mutate(both_chip_sets, chip_id = as.character(chip_id)),
                  by = c("prompt" = "spanish")) %>%
        mutate(spanish = prompt,
               correct = ifelse(str_detect(chip_id, response), 1, 0),
               correct = ifelse(!is.na(response), correct, ifelse(response_num == 1, 0, NA))) %>%
        left_join(spanish_boundary %>%
                    mutate(`Chip ID_2` = as.character(`Chip ID_2`)), 
                  by = c("prompt" = "Color_1", "response" = "Chip ID_2"))
    }
    
    
  } else if (first(df$task) == "Production") {
    df <- df %>%
      filter(response_num == 1 | !is.na(response)) %>%
      group_by(subj, task, prompt) %>%
      mutate(response_order = ifelse(row_number() == 1,
                                     ifelse(row_number() == max(row_number()), 'only', 'first'),
                                     ifelse(row_number() == max(row_number()), 'last', 'middle'))) %>%
      ungroup() %>%
      mutate(
        prompt = as.character(forcats::fct_collapse(prompt,
                                            `297` = c("amarillo", "AM"),
                                            `274` = c("BL", "blanco"),
                                            `291` = c("AZ"),
                                            `1` = c("celeste"),
                                            `46` = c("GR"),
                                            `266` = c("MRN"),
                                            `320` = c("mierda sol"),
                                            `325` = c("morado", "MRD"),
                                            `121` = c("NR"),
                                            `312` = c("NG", "negro"),
                                            `245` = c("rojo", "RJ"),
                                            `65` = c("RS"),
                                            `234` = c("VD", "verde"))),
        response = do.call(forcats::fct_collapse, list(response, !!!spelling_list))
        )
             
             
    if (first(df$language) == "Shipibo") {
      df <- df %>%
        left_join(adult_naming_consensus %>% ungroup() %>%
                    add_row(chip_id = 234, color_cat = c("Pei", "Xo")) %>%
                    add_row(chip_id = 320, color_cat = c("Barin Poi")) %>%
                    group_by(chip_id) %>%
                    summarise(terms = paste(color_cat, collapse = ", ")) %>%
                    mutate(chip_id = as.character(chip_id)),
                  by = c("prompt" = "chip_id")) %>%
        mutate(correct = ifelse(str_detect(terms, str_replace_na(response)), 1, 0),
               correct = ifelse(!is.na(response), correct, ifelse(response_num == 1, 0, NA)),
               correct = ifelse(prompt == "325" & response == "Poa", 1, correct)) %>%
        left_join(both_chip_sets %>%
                    mutate(chip_id = as.character(chip_id)), 
                  by = c("prompt" = "chip_id")) %>%
        mutate(correct_switch = ifelse(str_detect(spanish, str_replace_na(response)), 1, 0),
               correct_switch = ifelse(spanish == "Celeste" & response == "Azul", 1, correct_switch),
               correct_switch = ifelse(spanish == "Morado" & response == "Violeta", 1, correct_switch)) %>%
        left_join(shipibo_boundary, 
                  by = c("shipibo" = "Color_1", "response" = "Color_2"))
      
    } else if (first(df$language) == "Spanish") {
      df <- df %>%
        left_join(both_chip_sets %>%
                    mutate(chip_id = as.character(chip_id)),
                  by = c("prompt" = "chip_id")) %>%
        mutate(correct = ifelse(str_detect(spanish, str_replace_na(response)), 1, 0),
               correct = ifelse(!is.na(response), correct, ifelse(response_num == 1, 0, NA)),
               correct = ifelse(spanish == "Azul" & response == "Celeste", 1, correct),
               correct = ifelse(spanish == "Morado" & response == "Violeta", 1, correct),
               correct_switch = ifelse(str_detect(shipibo, str_replace_na(response)), 1, 0),
               correct_switch = ifelse(spanish == "Azul" & response %in% c("Nai", "Yankon"), 1, correct_switch),
               correct_switch = ifelse(spanish == "Verde" & response %in% c("Pei", "Xo", "Yankon"), 1, correct_switch),
               correct_switch = ifelse(spanish == "Morado" & response %in% c("Ami", "Poa", "Kari"), 1, correct_switch)) %>%
        left_join(spanish_boundary, by = c("spanish" = "Color_1", "response" = "Color_2"))

      
    }
    

       
  }
  
  df <- df %>%
    mutate_at(vars(starts_with("chip")), as.character) %>%
    select(language:age_interval, starts_with("response"), starts_with("correct"), spanish, adjacency, dist)
  
  return(df)
}


```


```{r}

if (refresh_data) {
  
  child_data <- bind_rows("Shipibo" = read_csv("../data/Current_Data/shipibo_children_colors_participants.csv") %>%
                            left_join(read_csv("../data/Current_Data/shipibo_children_colors_data.csv"), by = 'subj'),
                          "Spanish" = read_csv("../data/Current_Data/spanish_children_colors_participants.csv") %>%
                            left_join(read_csv("../data/Current_Data/spanish_children_colors_data.csv"), by = 'subj'),
                          .id = "language") %>% 
    mutate(age = ifelse(is.na(age), as.numeric(as.character(edad)), as.numeric(as.character(age))),
           task = ifelse(task == 1, "Production", ifelse( task == 2, "Comprehension", NA)),
           age_interval = floor(age/age_int)*age_int) %>%
    gather("response_num", "response", response_1:response_4) %>%
    mutate(response_num = as.numeric(as.character(gsub("response_", "", response_num)))) %>%
    split(list(.$language, .$task)) %>%
    map_df(clean_child_data, min_consensus) %>%
    mutate(correct = ifelse(response_num == 1 & is.na(response), 0, correct),
           adjacency = ifelse(correct == 1, NA, adjacency),
           dist = ifelse(correct == 1, NA, dist))
  
    feather::write_feather(child_data, "../intermediates/child_data.csv")

} else {
  child_data <- feather::read_feather("../intermediates/child_data.csv")
}


```

```{r}

cd <- child_data %>%
  mutate(age_scaled = scale(.$age, scale = FALSE)[,1]) %>%
  select(language, género, subj, `lugar de grabación`, age, age_scaled, age_interval, task, prompt, spanish, response_num, response, response_order, correct, correct_switch, adjacency, dist) %>%
  rename(gender = género, location = `lugar de grabación`) %>%
  mutate(correct = ifelse(task == "Comprehension" & language == "Shipibo" & prompt == "Yankon" & response_num == "2" & is.na(response), 0, correct)) %>%
  mutate_if(is.character, factor) %>%
  group_by_at(vars(language:spanish, response_order)) %>%
  mutate(correct_either = correct + ifelse(!is.na(correct_switch), correct_switch, 0)) %>%
  summarise(num_responses = n(),
            response = str_c(response, collapse = ", "),
            correct = mean(correct, na.rm = T),
            correct_either = mean(correct_either, na.rm = T),
            wrong_adjacent = mean(adjacency, na.rm = T),
            wrong_euc_dist = mean(dist, na.rm = T)) %>%
  mutate_if(is.double, funs(replace(., is.nan(.), NA)))

feather::write_feather(cd, "../intermediates/processed_data.csv")


# pbt_mod <- glmer(correct ~ age_scaled * task + (task | subj) + (task | prompt), data=cd,
#                  family = "binomial")
# 
# summary(pbt_mod)

```

